## directories ##

working_dir: "temp/"

results_dir: "results/"

data_dir: "../data/"

units : "units.tsv"

## genome reference ##

genome_fasta_url : "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M17/GRCm38.primary_assembly.genome.fa.gz"
gene_gtf_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz"
HMMRATAC: "https://github.com/LiuLabUB/HMMRATAC/releases/download/1.2.10/HMMRATAC_V1.2.10_exe.jar"


## trimmomatic ##
trimmomatic:
  adapters:               "adapters.fasta"
  seedMisMatches:         '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold:    '10'
  LeadMinTrimQual:        '3'
  TrailMinTrimQual:       '3'
  windowSize:             '4'
  avgMinQual:             '15'
  minReadLength:          '40'
  phred:                  '-phred33'

# bowtie2 parameters
bowtie2:
  params:
    mode:             "--local"
    sensitivity:      "--very-sensitive-local"
    max_fragment_len: "--maxins 500"                # maximum fragment length for valid paired-end alignments
    min_fragment_len: "--minins 80"                 # minimum fragment length for valid paired-end alignments
    verbose:          "-q"

# genome.info
hmmratac:
  genome.info: "genome.info"

# macs2
macs2:
  genomesize: "--gsize mm"
  format: "--format BAMPE"
  outdir: "results/macs2"

# bamCoverage
# binSize parameters is set to 1000bp to test quickly the pipeline. Change to a lower value with real samples.
bamCoverage:
  effectiveGenomeSize: "2652783500"
  normalization: "RPKM" # Alterntively choose "RPGC", "CPM", "BPM". If you don't specify this argument, by default no normalization method will be used.
  binSize: "50"

# computeMatrix
ComputeMatrix:
  GTF: "gencode.vM25.annotation.gtf"
  binSize: "1000" # Test the pipelin with binSize=1000; please set it at a small number (e.g.10) when run it with real data.
  afterRegionStartLength: "3000"
  beforeRegionStartLength: "3000"
  referencePoint: "TSS"
  numberOfProcessors: "10"

# plotHeatmap
plotHeatmap:
  dpi: "100"
  yMin: "0"
  yMax: "50" # Set a proper number to make the heatmap profile look better.
  refPointLabel: "TSS" # Specify the reference point label by yourself, e.g. "Center".
  colorList: "'white, blue'" # Blue in center, surrounded by white.

# plotProfile
plotProfile:
  dpi: "100"
  colors: "red blue yellow green" # Please define colors of profile. The number of colors should be consistent with the number of samples.

# plotCorrelation
plotCorrelation:
  corMethod: "pearson" # Alternatively "spearman" could be used.
  whatToPlot: "heatmap" # Alterntively "scatterplot" could be used.

# bamPEFragmentSize
bamPEFragmentSize:
  binSize: "1000"  #This is default value.
  numberOfProcessors: "10" #Grant 10 processors to make it run faster.
  plotFileFormat: "pdf" # pdf has higher resolution than png.
  samplesLabel: "sample1 sample2 sample3 sample4" # General labels are used here. You can change sample names.
  plotTitle: "'Fragment size of PE ATAC-seq data'" # General title is used here. You can name it.
