## directories ##

working_dir: "temp/"

results_dir: "results/"

data_dir: "../data/"

units : "units.tsv"

## genome reference ##

genome_fasta_url : "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M17/GRCm38.primary_assembly.genome.fa.gz"
HMMRATAC: "https://github.com/LiuLabUB/HMMRATAC/releases/download/1.2.10/HMMRATAC_V1.2.10_exe.jar"


## trimmomatic ##
trimmomatic:
  adapters:               "adapters.fasta"
  seedMisMatches:         '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold:    '10'
  LeadMinTrimQual:        '3'
  TrailMinTrimQual:       '3'
  windowSize:             '4'
  avgMinQual:             '15'
  minReadLength:          '40'
  phred:                  '-phred33'

# bowtie2 parameters
bowtie2:
  params:
    mode:             "--local"
    sensitivity:      "--very-sensitive-local"
    max_fragment_len: "--maxins 500"                # maximum fragment length for valid paired-end alignments
    min_fragment_len: "--minins 80"                 # minimum fragment length for valid paired-end alignments
    verbose:          "-q"

# genome.info
hmmratac:
  genome.info: "genome.info"

# macs2
macs2:
  genomesize: "--gsize mm"
  format: "--format BAMPE"
  outdir: "results/macs2"

# bamCoverage
# binSize parameters is set to 1000bp to test quickly the pipeline. Change to a lower value with real samples.
bamCoverage:
  effectiveGenomeSize: "2652783500"
  normalization: "RPKM"
  binSize: "1000"
